export const requiredPermissions = [
  {
    key: 'notifications',
    title: 'Notifications',
    description: 'Alerts you when an alarm starts.',
    icon: 'notifications-outline',
    backgroundColor: '#FFF0E8',
    iconColor: '#FF7A18',
  },
  {
    key: 'camera',
    title: 'Camera',
    description: 'Used to complete your wake-up photo challenge.',
    icon: 'camera-outline',
    backgroundColor: '#F1EAFE',
    iconColor: '#8B5CF6',
  },
  {
    key: 'exactAlarm',
    title: 'Exact Alarms',
    description: 'Allows alarms to ring at the exact time.',
    icon: 'alarm-outline',
    backgroundColor: '#EAF5FF',
    iconColor: '#39A8FF',
  },
  {
    key: 'fullScreenAlarm',
    title: 'Full Screen / Overlay',
    description: 'Shows the alarm screen over other apps.',
    icon: 'phone-portrait-outline',
    backgroundColor: '#F1EAFE',
    iconColor: '#8B5CF6',
  },
  {
    key: 'batteryOptimization',
    title: 'Battery Access',
    description: 'Keeps alarms reliable when your phone is locked.',
    icon: 'battery-charging-outline',
    backgroundColor: '#EAFBF0',
    iconColor: '#6BCB4B',
  },
];
