/**
 * SnapWake Theme System - Premium Redesign
 */

import { tokens } from "./tokens";

export const THEMES = {
  // Midnight: The new primary premium theme (Deep Navy + Soft Purple)
  midnight: {
    id: "midnight",
    name: "Midnight",
    emoji: "🌌",
    light: {
      primary:       tokens.colors.primary,
      primaryLight:  "#F5F3FF",
      primarySoft:   "#EDE9FE",
      accent:        tokens.colors.accent,
      bg:            "#F6F7FB",
      card:          "#FFFFFF",
      cardBorder:    "#E2E8F0",
      surface:       "#F1F5F9",
      divider:       "#F1F5F9",
      heroCard:      tokens.colors.background,
      heroBorder:    tokens.colors.surface,
      heroNeon:      tokens.colors.primaryLight,
      heroAccent:    "rgba(123,97,255,0.18)",
      heroCountdown: "rgba(167,139,250,0.1)",
      textPrimary:   "#0F172A",
      textSecondary: "#475569",
      textMuted:     "#94A3B8",
      danger:        tokens.colors.danger,
      warning:       tokens.colors.warning,
      statusBar:     "dark",
    },
    dark: {
      primary:       tokens.colors.primary,
      primaryLight:  "rgba(123, 97, 255, 0.15)",
      primarySoft:   "rgba(123, 97, 255, 0.1)",
      accent:        tokens.colors.accent,
      bg:            tokens.colors.background,
      card:          tokens.colors.surface,
      cardBorder:    tokens.colors.border,
      surface:       tokens.colors.surfaceElevated,
      divider:       tokens.colors.divider,
      heroCard:      tokens.colors.surfaceElevated,
      heroBorder:    tokens.colors.surface,
      heroNeon:      tokens.colors.primaryLight,
      heroAccent:    "rgba(123, 97, 255, 0.15)",
      heroCountdown: "rgba(155, 138, 255, 0.08)",
      textPrimary:   tokens.colors.textPrimary,
      textSecondary: tokens.colors.textSecondary,
      textMuted:     tokens.colors.textMuted,
      danger:        tokens.colors.danger,
      warning:       tokens.colors.warning,
      statusBar:     "light",
    },
  },

  // Forest: Refined green theme
  forest: {
    id: "forest",
    name: "Forest",
    emoji: "🌿",
    light: {
      primary:       "#059669",
      primaryLight:  "#ECFDF5",
      primarySoft:   "#D1FAE5",
      accent:        "#7B61FF",
      bg:            "#F0FDF4",
      card:          "#FFFFFF",
      cardBorder:    "#D1FAE5",
      surface:       "#F0FDF4",
      divider:       "#F0FDF4",
      heroCard:      "#064E3B",
      heroBorder:    "#065F46",
      heroNeon:      "#6EE7B7",
      heroAccent:    "rgba(5,150,105,0.2)",
      heroCountdown: "rgba(110,231,183,0.1)",
      textPrimary:   "#064E3B",
      textSecondary: "#065F46",
      textMuted:     "#34D399",
      danger:        "#EF4444",
      warning:       "#F59E0B",
      statusBar:     "dark",
    },
    dark: {
      primary:       "#10B981",
      primaryLight:  "rgba(16,185,129,0.15)",
      primarySoft:   "rgba(16,185,129,0.1)",
      accent:        "#7B61FF",
      bg:            "#022C22",
      card:          "#064E3B",
      cardBorder:    "#065F46",
      surface:       "#065F46",
      divider:       "#065F46",
      heroCard:      "#022C22",
      heroBorder:    "#064E3B",
      heroNeon:      "#6EE7B7",
      heroAccent:    "rgba(16,185,129,0.15)",
      heroCountdown: "rgba(110,231,183,0.08)",
      textPrimary:   "#ECFDF5",
      textSecondary: "rgba(236,253,245,0.6)",
      textMuted:     "rgba(236,253,245,0.38)",
      danger:        "#F87171",
      warning:       "#FBB040",
      statusBar:     "light",
    },
  },
};

export const THEME_LIST = Object.values(THEMES);
export const DEFAULT_THEME_ID = "midnight";
